### ISSUE TITLE
deleting messages

### ISSUE THREAD

**Issue by Bergiu** [TheWildBear/bigDataTelgrambot#25]
Remove the feature, that removes the messages after a timeout. This happens for example on reply of the /top command.

**Comment by TheWildBear** [comment]
Already added & Fixed with commit: 0de8cd645e5a45de521bc159c77534d7cff0d803

**Comment by Bergiu** [comment]
Eather it's not fixed, or you're hosting an old version. Now it also removes the reply of /top

**Comment by TheWildBear** [comment]
Oh Sry wrong message :sweat_smile: I believe that will continue to work this Way... Other option would be sending the msg directly in private chat
